# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363d2441622730405ab462cbfe671519e6a519f141d0a9925732c0b0d500c021394810c07b0bcd8c81255e84de7a88b5097218815b88041884357f4bc627b33d

test:
  secret_key_base: a508568e971119f61fd9e11b192c22cc1dc65d862aee29a7705a26ba3d979e432e57f56cd36b8b69fc30cb84fec3eeaaeb7fc5debcd03925c23d2893051cf4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
